(function(){
  const PERMS={
    'overview.view':'الرئيسية والتقارير العامة','sales.view':'تقارير المبيعات','sales.invoice.create':'إنشاء فاتورة بيع','sales.targets.edit':'تعديل الأهداف والتحقيق','customers.view':'تقارير العملاء وكشوف الحساب','customers.edit':'إضافة وتعديل العملاء','purchases.view':'تقارير المشتريات','purchases.receipt.create':'إذن استلام معدة','production.view':'تقارير الإنتاج','production.order.create':'أمر إنتاج','finance.view':'التقارير المالية','finance.edit':'تعديل الإدارة المالية','inventory.view':'تقارير المخزن','inventory.edit':'تعديل المخزن','hr.view':'مشاهدة الموظفين','hr.create':'إضافة موظفين','hr.edit':'تعديل بيانات الموظفين','hr.delete':'حذف الموظفين','hr.documents':'رفع مستندات الموظفين','hr.attendance':'تسجيل الحضور والانصراف','worker.view':'مشاهدة العمال والفنيين','worker.create':'إضافة العمال والفنيين','worker.edit':'تعديل حسابات العمال','worker.delete':'حذف العمال','worker.payments':'تسجيل دفعات العمال','crm.view':'تقارير CRM','crm.edit':'تعديل CRM','products.view':'مشاهدة صور المنتجات','products.edit':'إدارة صور المنتجات','users.manage':'إدارة المستخدمين والصلاحيات'
  };
  const style=document.createElement('style'); style.textContent='#erp-auth{position:fixed;inset:0;background:#F4FAFB;z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px}#erp-auth .box,#erp-users .box{background:#fff;border:1px solid #E7E1D3;border-radius:16px;padding:28px;max-width:700px;width:100%;box-shadow:0 12px 40px #0B3D4522;direction:rtl}#erp-auth .box{max-width:440px}#erp-auth h2,#erp-users h2{font-family:Tajawal,Cairo,sans-serif;color:#0B3D45;margin:0 0 8px}#erp-auth p{font-size:13px;color:#6B7280;line-height:1.8}#erp-auth input,#erp-users input,#erp-users select{display:block;width:100%;margin:10px 0;padding:11px;border:1px solid #E7E1D3;border-radius:8px;font-family:Cairo;font-size:14px}#erp-auth .pass-wrap{position:relative}#erp-auth .pass-wrap input{padding-left:80px}#erp-auth .show-pass{position:absolute;left:8px;top:17px;border:0;background:transparent;color:#0B3D45;cursor:pointer;font-family:Cairo;font-size:11px}#erp-auth button,#erp-users button{border:0;border-radius:8px;background:#0B3D45;color:#fff;padding:11px 16px;font-family:Cairo;font-weight:700;cursor:pointer}#erp-auth .submit{width:100%}#erp-auth .err{color:#C1443D;font-size:12px;margin:8px 0;min-height:18px}.cloud-user{font-size:11px;color:#6FC3D6;margin-top:4px}#erp-users{position:fixed;inset:0;background:#0B3D4588;z-index:5000;display:flex;align-items:flex-start;justify-content:center;padding:30px 15px;overflow:auto}#erp-users .close{float:left;background:transparent;color:#6B7280;font-size:22px;padding:0}#erp-users .perm-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:8px;background:#F4FAFB;padding:12px;border-radius:10px;max-height:260px;overflow:auto}.perm-grid label{font-size:12px}.user-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:9px;border-bottom:1px solid #E7E1D3;font-size:13px}.user-row button{padding:5px 9px;font-size:11px;background:#C1443D}.admin-nav{margin:10px 12px!important;background:#1A6B78!important;color:#fff!important}'; document.head.appendChild(style);
  const auth=document.createElement('div'); auth.id='erp-auth'; auth.innerHTML='<div class="box"><h2>نظام مصنع العاشر</h2><p id="erp-auth-note">جاري الاتصال بالنظام المركزي...</p><div id="erp-auth-form"></div><div class="err" id="erp-auth-error"></div></div>'; document.body.appendChild(auth);
  const form=document.getElementById('erp-auth-form'),note=document.getElementById('erp-auth-note'),error=document.getElementById('erp-auth-error'); let syncTimer,currentUser;
  function passwordField(id,placeholder){return '<div class="pass-wrap"><input id="'+id+'" type="password" placeholder="'+placeholder+'" autocomplete="current-password"><button type="button" class="show-pass" data-for="'+id+'">إظهار</button></div>'}
  function wirePasswordButtons(root){root.querySelectorAll('.show-pass').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.for);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'إظهار':'إخفاء';})}
  function setForm(setup){note.textContent=setup?'أنشئ حساب المدير الأول للنظام. بعد ذلك يمكنك إضافة باقي المستخدمين.':'سجّل الدخول للوصول إلى بيانات المصنع من أي جهاز.';form.innerHTML=(setup?'<input id="erp-name" placeholder="اسم المدير" autocomplete="name">':'')+'<input id="erp-user" placeholder="اسم المستخدم" autocomplete="username">'+passwordField('erp-pass','كلمة المرور')+'<button class="submit" id="erp-submit">'+(setup?'إنشاء حساب المدير':'تسجيل الدخول')+'</button>';wirePasswordButtons(form);document.getElementById('erp-submit').onclick=async()=>{error.textContent='';const username=document.getElementById('erp-user').value.trim(),password=document.getElementById('erp-pass').value,body={username,password};if(setup)body.displayName=document.getElementById('erp-name').value.trim()||username;try{const r=await fetch(setup?'/api/auth/setup':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر التنفيذ');await beginSync(d.user)}catch(e){error.textContent=e.message}}}
  function can(p){return currentUser?.role==='admin'||!!currentUser?.permissions?.[p]}
  window.erpCan=can;
  function gateUI(){document.querySelectorAll('#nav button[data-tab]').forEach(b=>{const p=b.dataset.tab+'.view';b.style.display=can(p)?'':'none'});if(currentUser?.role==='admin'||can('users.manage')){if(!document.querySelector('.admin-nav')){const b=document.createElement('button');b.className='admin-nav';b.textContent='⚙ إدارة المستخدمين والصلاحيات';b.onclick=openUsers;document.getElementById('nav').appendChild(b)}}document.addEventListener('click',guardAction,true)}
  function guardAction(e){const b=e.target.closest('button');if(!b||b.classList.contains('admin-nav'))return;const t=(b.textContent||'').trim();const rules=[[/فاتورة بيع|فاتورة مبيعات/,'sales.invoice.create'],[/إذن استلام معدة/,'purchases.receipt.create'],[/أمر إنتاج|أمر انتاج/,'production.order.create'],[/هدف|الأهداف والتحقيق/,'sales.targets.edit']];const hit=rules.find(x=>x[0].test(t));if(hit&&!can(hit[1])){e.preventDefault();e.stopImmediatePropagation();alert('ليس لديك صلاحية: '+PERMS[hit[1]]);return false}}
  async function beginSync(user){try{const r=await fetch('/api/state'),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل البيانات');currentUser=user;const local=STORE;if(d.state&&typeof d.state==='object'&&Object.keys(d.state).length){STORE=Object.assign({custom_txns:[],custom_accounts:[],expenses:[]},d.state);if(!STORE._hr_reset_v1){STORE.employees=[];STORE.attendance=[];STORE.hr_txns=[];STORE.salary_payments=[];STORE.advances=[];STORE._hr_reset_v1=true;await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:STORE})})}localStorage.setItem(STORE_KEY,JSON.stringify(STORE))}else if(local&&(local.custom_txns?.length||local.custom_accounts?.length||local.expenses?.length)){await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:local})})}auth.remove();document.body.dataset.user=user.username;const title=document.querySelector('#topbar .sub');if(title){const badge=document.createElement('div');badge.className='cloud-user';badge.textContent='متصل: '+user.displayName;title.appendChild(badge)}gateUI();if(typeof goTo==='function'){const active=document.querySelector('#nav button.active');goTo(active?.dataset.tab||'overview')}}catch(e){error.textContent=e.message;setForm(false)}}
  window.saveStore=function(){try{localStorage.setItem(STORE_KEY,JSON.stringify(STORE));clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{try{await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:STORE})})}catch(e){console.error('تعذر مزامنة البيانات',e)}},300)}catch(e){console.error('تعذر الحفظ',e)}};
  function openUsers(){if(!can('users.manage'))return;let old=document.getElementById('erp-users');if(old)old.remove();const el=document.createElement('div');el.id='erp-users';el.innerHTML='<div class="box"><button class="close" onclick="document.getElementById(\'erp-users\').remove()">×</button><h2>إدارة المستخدمين والصلاحيات</h2><p class="small-note">أنشئ مستخدمًا وحدد له الوظائف المسموح بها. المدير لديه كل الصلاحيات.</p><div id="users-list">جاري التحميل...</div><hr><h3>إضافة مستخدم جديد</h3><input id="new-display" placeholder="الاسم الظاهر"><input id="new-username" placeholder="اسم المستخدم بالإنجليزية"><div class="pass-wrap">'+passwordField('new-password','كلمة المرور')+'</div><select id="new-role"><option value="staff">موظف بصلاحيات محددة</option><option value="admin">مدير كامل الصلاحيات</option></select><div class="perm-grid">'+Object.entries(PERMS).map(([k,v])=>'<label><input type="checkbox" data-perm="'+k+'"> '+v+'</label>').join('')+'</div><br><button id="create-user">حفظ المستخدم</button><div id="users-error" class="err"></div></div>';document.body.appendChild(el);wirePasswordButtons(el);loadUsers();document.getElementById('create-user').onclick=async()=>{const permissions={};el.querySelectorAll('[data-perm]:checked').forEach(x=>permissions[x.dataset.perm]=true);const body={displayName:document.getElementById('new-display').value,username:document.getElementById('new-username').value,password:document.getElementById('new-password').value,role:document.getElementById('new-role').value,permissions};const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok){document.getElementById('users-error').textContent=d.error;return}document.getElementById('users-error').textContent='تم إنشاء المستخدم';loadUsers()}}
  async function loadUsers(){const box=document.getElementById('users-list');if(!box)return;const r=await fetch('/api/users'),d=await r.json();if(!r.ok){box.textContent=d.error;return}box.innerHTML=d.users.map(u=>'<div class="user-row"><span><b>'+u.displayName+'</b> ('+u.username+') — '+(u.role==='admin'?'مدير':'موظف')+'</span>'+(u.id===currentUser.id?'': '<button onclick="window.deleteERPUser('+u.id+')">حذف</button>')+'</div>').join('')}
  window.deleteERPUser=async id=>{if(!confirm('حذف هذا المستخدم؟'))return;await fetch('/api/users/'+id,{method:'DELETE'});loadUsers()}; window.openERPUsers=openUsers;
  fetch('/api/auth/status').then(r=>r.json()).then(d=>setForm(!!d.setupRequired)).catch(()=>{error.textContent='تعذر الوصول للخادم. أعد تحميل الصفحة.';setForm(false)});
})();
